config/routes.rb
Studentreport::Application.routes.draw do
  resources :groups
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :reports
  resources :students
  resources :subjects
  get "welcome/index"
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'students#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/report.rb
class Report < ActiveRecord::Base
belongs_to :student

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/student.rb
class Student < ActiveRecord::Base
has_many :reports
end

app/models/subject.rb
class Subject < ActiveRecord::Base
has_many :usersubjects
has_many :users, :through => :usersubjects
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :reports
    has_many :usersubjects
	has_many :subjects, :through => :usersubjects
attr_reader :subject_tokens
def subject_tokens=(ids)
	self.subject_ids = ids.split(",")
	
end
end

app/models/usersubject.rb
class Usersubject < ActiveRecord::Base
	attr_accessor :subject_ids
	belongs_to :user
	belongs_to :subject
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ subject_tokens: [] }, :email, :password, :password_confirmation, :subject_tokens) }
end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
  	@group = params[:id]
  	@students = Student.where(:group => @group).order(last_name: :asc)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    else
      # remove the virtual current_password attribute
      # update_without_password doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case their password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
      params[:user][:password].present?
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @students = Student.all
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
    @student = Student.find(@report.student_id)
  end

  # GET /reports/new
  def new
    @report = Report.new
    @student = Student.find(params[:student_id])

  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:reason, :teacher_experience, :subject, :user_id, :student_experience, :student_id, :evaluation_date, :updated)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
before_action :authenticate_user!
  def index
	 respond_to do |format|
	    format.html
	    format.json { render json: StudentDatatable.new(view_context) }
	  end
  end

  def show
  	@student = Student.find(params[:id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
  @subjects = Subject.order(:name)
	  respond_to do |format|
	    format.html
	    format.json { render json: @subjects.where("name like ?", "%#{params[:q]}%")}
	  end
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/usersubjects_helper.rb
module UsersubjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/show.html.erb
<h1><%=@group%></h1>
<table class="table table-condensed table-hover">
	<thead>
		<th>Namn</th>
		<th>Antal utredningar</th>
		

	</thead>
	<tbody>
		<% @students.each do |s|%>
			<tr <% if s.reports.count > 3 %> class="danger" <% end -%> >
				<td><%= link_to s.first_name, student_path(s)%> <%= link_to s.last_name, student_path(s)%></td>
				<td><%= s.reports.count%></td>
			</tr>
		<% end -%>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Studentreport</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
<%= render 'shared/menu' %>

<%= yield %>
</div>
</body>
</html>

app/views/reports/_form.html.erb
<%= form_for @report, :html => {:class=> "grid-form"} do |f| %>
<%= f.hidden_field :student_id, :value => @student.id%>    
<%= f.hidden_field :user_id, :value => current_user.id%>
    <fieldset>
        <legend>Pedagogisk utredning för <%= @student.first_name%> <%= @student.last_name%> </legend>
            <div data-row-span="3">
            <div data-field-span="1">
                <label><%= f.label :evaluation_date, "Utvärderingsdatum" %></label>
               <%= f.text_field :evaluation_date, :id => "timepicker" %>
            </div><div data-field-span="1">
                <label><%= f.label :updated, "Utvärderad?" %></label>
               <%= f.check_box :updated %>
            </div>
                        <div data-field-span="1">
                <label><%= f.label :subject, "Ämne" %></label>
                <%= f.collection_select :subject, current_user.subjects.order(:name), :name, :name, {:include_blank => 'Välj ämne'} %>
             
            </div>
        </div>
        <div data-row-span="1">
            <div data-field-span="1">
                <label><%= f.label :reason, "Anledning till utredning" %></label>
                <%= f.text_area :reason %>
            </div>
          </div>
        <div data-row-span="1">
            <div data-field-span="1">
                <label><%= f.label :teacher_experience, "Lärarens erfarenhet" %></label>
                <%= f.text_area :teacher_experience %>
            </div>
          </div>
          
          <div data-row-span="1">
            <div data-field-span="1">
                <label><%= f.label :student_experience, "Elevens erfarenhet" %></label>
                <%= f.text_area :student_experience %>
            </div>
          </div>
    
    <%= f.submit %>
        </div>
    </fieldset>

<% end -%>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= form_for @report, :html => {:class=> "grid-form"} do |f| %>

    <fieldset>
        <legend>Pedagogisk utredning för</legend>
               <div data-row-span="3">
            <div data-field-span="1">
                <label><%= f.label :evaluation_date, "Utvärderingsdatum" %></label>
               <%= f.text_field :evaluation_date, :id => "timepicker" %>
            </div><div data-field-span="1">
                <label><%= f.label :updated, "Utvärderad?" %></label>
               <%= f.check_box :updated %>
            </div>
                        <div data-field-span="1">
                <label><%= f.label :subject, "Ämne" %></label>
                <%= f.collection_select :subject, current_user.subjects.order(:name), :name, :name, {:include_blank => 'Välj ämne'} %>
             
            </div>
        </div>
        <div data-row-span="1">
            <div data-field-span="1">
                <label><%= f.label :reason, "Anledning till utredning" %></label>
                <%= f.text_area :reason %>
            </div>
          </div>
        <div data-row-span="1">
            <div data-field-span="1">
                <label><%= f.label :teacher_experience, "Lärarens erfarenhet" %></label>
                <%= f.text_area :teacher_experience %>
            </div>
          </div>
          
          <div data-row-span="1">
            <div data-field-span="1">
                <label><%= f.label :student_experience, "Elevens erfarenhet" %></label>
                <%= f.text_area :student_experience %>
            </div>
          </div>
        <div data-row-span="3">
            <div data-field-span="1">
                <label><%= f.label :evaluation_date, "Utvärderingsdatum" %></label>
               <%= f.text_field :evaluation_date, :id => "timepicker" %>
             
            </div><div data-field-span="1">
                <label><%= f.label :updated, "Utvärderad?" %></label>
               <%= f.check_box :updated %>
             
            </div>
        </div>
    <%= f.submit %>
        </div>
    </fieldset>

<% end -%>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table class="table">
  <thead>
    <tr>
      <th>Förnamn</th>
      <th>Efternamn</th>
      <th>Personnummer</th>
      <th>Antal utredningar</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.socialsecurity %></td>
        <td><%= student.reports.count %></td>
        <td><%= link_to "Skapa utredning", new_report_path(:student_id => student.id), :class => "btn btn-black btn-xs"%></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<h3>Utvärdering för <%= @student.first_name%> <%=@student.last_name%></h3>


<p><%= @report.subject %></p>
<p id="notice"><%= notice %></p>
<div class="report-field">
  <div class="report-field-header">ANLEDNING TILL UTREDNING</div>
  <div class="report-field-content">
    <%= @report.reason %>
  </div>
</div>

<div class="report-field">
  <div class="report-field-header">LÄRARENS ERFARENHET</div>
  <div class="report-field-content">
  <%= @report.teacher_experience %>
  </div>
</div>
<div class="report-field">
  <div class="report-field-header">Elevens ERFARENHET</div>
  <div class="report-field-content">
  <%= @report.student_experience %>
  </div>
</div>
<div class="report-field small-field<% if @report.evaluation_date < Time.now %> bs-callout bs-callout-danger <% end -%>">
  <div class="report-field-header">Datum för utvärdering <% if @report.evaluation_date < Time.now %> <span class="report-danger">(Utvärderingsdatum är överskridet!)</span><% end -%></div>
  <div class="report-field-content">

   <%= @report.evaluation_date %>
  </div>
</div>




<p>
  <strong>Updated:</strong>
<% if @report.updated?%>
  Utredningen är ännu inte utvärderad.
  <%else%>
  Utredningen är updaterad.
</p>
<% end -%>
<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/shared/_menu.html.erb
<% if user_signed_in?%>
<ul id="nav"class="nav nav-pills">
  <li class="<%= 'active' if params[:controller] =='welcome' %>"><a href="<%= root_path%>">Hem</a> </li>
   <li class="<%= 'active' if params[:controller] =='students' %>"><a href="<%= students_path %>">Elever</a> </li>
  <li class="<%= 'active' if params[:controller] =='reports' %>"><a href="<%= reports_path %>">Utredning</a> </li>
  <li class="<%= 'active' if params[:controller] =='users' %>"><a href="<%= edit_user_registration_path %>">Profil</a> </li>
  <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>


</ul>
<% end -%>

app/views/students/index.html.erb
<h1>Elever</h1>

<table class="table" id="students-table", data-source="<%= students_path(format: :json) %>">
  <thead>
    <tr>
      <th>Förnamn</th>
      <th>Efternamn</th>
      <th>Klass</th>
      
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/students/show.html.erb
<h1><%= @student.first_name%> <%= @student.last_name%></h1>
<%= link_to "Skapa utredning", new_report_path(:student_id => @student.id), :class => "btn btn-black btn-xs"%>
<% unless @student.reports.blank?%>
	<table>
		<tbody>
			<thead>
				<th>Skapad</th>
			</thead>
			<%@student.reports.each do |report|%>
				<tr>
					<td><%=link_to(report.created_at, report_path(report))%></td>
				</tr>	
			<% end -%>
		</tbody>
	</table>
<% end -%>

app/views/welcome/index.html.erb
<h1>TEST</h1>